export const CHANGE_BANNER = 'recommend/CHANGE_BANNER'

export const CHANGE_RECOMMEND_LIST = 'recommend/RECOMMEND_LIST'
export const CHANGE_RECOMMEND_NEW_SONG_LIST = 'recommend/NEW_SONG_LIST'
export const CHANGE_RECOMMEND_DJ_LIST = 'recommend/DJ_LIST'

export const CHANGE_CURRENT_PLAYLIST = 'album/CHANGE_CURRENT_PLAYLIST'
export const CHANGE_ENTER_LOADING = 'album/CHANGE_ENTER_LOADING'
